version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_data:/bitnami
  wordpress:
    # image: bitnami/wordpress:latest
    build:
      context: .
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - wordpress_data:/bitnami

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

# version: '3.1'

# services:

#   wordpress:
#     image: wordpress
#     restart: always
#     ports:
#       - 8080:80
#     environment:
#       WORDPRESS_DB_HOST: db
#       WORDPRESS_DB_USER: exampleuser
#       WORDPRESS_DB_PASSWORD: examplepass
#       WORDPRESS_DB_NAME: exampledb
#     volumes:
#       - ./plugins/:/var/www/html/wp-content/plugins/

#   db:
#     image: mysql:5.7
#     restart: always
#     environment:
#       MYSQL_DATABASE: exampledb
#       MYSQL_USER: exampleuser
#       MYSQL_PASSWORD: examplepass
#       MYSQL_RANDOM_ROOT_PASSWORD: '1'
